data:
  Xdim_flow: 2
  
CNF:
  hk_blocks: [10]
  S_ls: [5] 
  vfield_style: 'tree' 

training:
  ntr: 100000
  nte: 10000
  add_diffuse: None
  load_checkpoint: False
  warm_start: True 
  batch_size: 2000 
  block_idxes: [1]
  clip_grad: True
  tot_iters: 130
  lr: 0.0001
  sigma0: 0.02

eval:
  viz_freq: 13 
  folder_suffix: '' 