data:
  Xdim_flow: 2
  
CNF:
  hk_blocks: [0.25, 0.35, 0.49, 0.69, 0.96, 1.34, 1.88, 2.64]
  S_ls: [3,3,3,3,3,3,3,3] 
  vfield_style: 'tree' 

training:
  ntr: 2000000
  nte: 50000
  add_diffuse: None
  load_checkpoint: True
  warm_start: True 
  batch_size: 2000 
  block_idxes: [1,2,3,4,5,6,7,8]
  clip_grad: True
  tot_iters: 20000
  lr: 0.0001
  sigma0: 0.02

eval:
  viz_freq: 2500 
  folder_suffix: '' 